package dev.pekelund.ai.mcp.domain;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;

/**
 * A note added to an incident's timeline.
 *
 * <p>Notes come in two varieties:
 * <ul>
 *   <li>{@code AUTO} — generated by an AI agent (triage analysis, diagnosis summary, etc.)</li>
 *   <li>{@code MANUAL} — written by a human on-call engineer</li>
 * </ul>
 *
 * <p>The complete note history forms a rich audit trail that feeds the post-mortem report.
 */
@Entity
@Table(name = "incident_notes",
        indexes = @Index(name = "idx_note_incident", columnList = "incident_id"))
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class IncidentNote {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "incident_id", nullable = false)
    private Long incidentId;

    @Column(columnDefinition = "TEXT", nullable = false)
    private String content;

    /**
     * {@code AUTO} for AI-generated notes, {@code MANUAL} for human notes.
     */
    @Builder.Default
    @Column(name = "note_type", nullable = false, length = 20)
    private String noteType = "MANUAL";

    /** Identifier of the author — agent name (e.g. {@code TriageAgent}) or a username. */
    @Column(length = 100)
    private String author;

    @Column(updatable = false)
    @Builder.Default
    private LocalDateTime createdAt = LocalDateTime.now();
}
