package dev.pekelund.ai.mcp.domain;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;

/**
 * Core incident entity — the central artefact in the platform.
 *
 * <p>An incident represents any unexpected degradation or outage. The lifecycle is:
 * <pre>
 *   OPEN → IN_PROGRESS → RESOLVED  (happy path)
 *              ↕
 *           ESCALATED
 * </pre>
 *
 * <p>AI-generated fields ({@link #aiSummary}, {@link #rootCause}, {@link #resolution})
 * are populated by the agent orchestrator and should be treated as suggestions that
 * a human on-call engineer reviews before acting.
 */
@Entity
@Table(name = "incidents")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Incident {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(nullable = false, length = 255)
    private String title;

    @Column(columnDefinition = "TEXT", nullable = false)
    private String description;

    /**
     * AI-determined severity: {@code CRITICAL}, {@code HIGH}, {@code MEDIUM}, {@code LOW}.
     * Initially {@code null} — set by the TriageAgent.
     */
    @Column(length = 20)
    private String severity;

    /**
     * Current lifecycle status. Defaults to {@code OPEN} on creation.
     */
    @Builder.Default
    @Column(nullable = false, length = 30)
    private String status = "OPEN";

    /** AI-determined category (e.g., {@code DATABASE}, {@code NETWORK}, {@code MEMORY}). */
    @Column(length = 100)
    private String category;

    /** Comma-separated list of service names identified as affected. */
    @Column(length = 500)
    private String affectedServices;

    /** Human who reported the incident. */
    @Column(length = 100)
    private String reportedBy;

    /** Engineer assigned to the incident. May be set by the AI or a human. */
    @Column(length = 100)
    private String assignedTo;

    /** Short narrative of what was done to resolve the incident. */
    @Column(columnDefinition = "TEXT")
    private String resolution;

    /** Root cause identified by the DiagnosisAgent. */
    @Column(columnDefinition = "TEXT")
    private String rootCause;

    /** Executive summary generated by the IncidentOrchestrator. */
    @Column(columnDefinition = "TEXT")
    private String aiSummary;

    @Column(updatable = false)
    @Builder.Default
    private LocalDateTime createdAt = LocalDateTime.now();

    @Builder.Default
    private LocalDateTime updatedAt = LocalDateTime.now();

    private LocalDateTime resolvedAt;

    @PreUpdate
    void onUpdate() {
        this.updatedAt = LocalDateTime.now();
    }
}
