package dev.pekelund.familiar.earth.tool;

import org.springframework.stereotype.Component;

/**
 * Deterministic computation tool: seismic_charge
 * Represents a "General Function" in the tool ecosystem.
 * Accumulates seismic energy for the iterative Earth agent.
 */
@Component
public class SeismicChargeTool {

    private static final double BASE_CHARGE = 15.0;
    private static final double VARIANCE = 10.0;

    /**
     * Performs a single seismic charge, returning the energy generated.
     *
     * @param iteration the current iteration number (affects charge power)
     * @return the energy generated by this charge
     */
    public double seismicCharge(int iteration) {
        // Deterministic formula with slight progression: energy grows with iterations
        double charge = BASE_CHARGE + (iteration * 2.5) + (Math.random() * VARIANCE);
        return Math.round(charge * 10.0) / 10.0;
    }
}
