package dev.pekelund.ai.agent.dto;

import dev.pekelund.ai.agent.domain.Incident;
import dev.pekelund.ai.agent.domain.IncidentNote;

import java.time.LocalDateTime;
import java.util.List;

/**
 * API response for a single incident, including its timeline notes.
 *
 * @param id               Database ID
 * @param title            Short summary
 * @param description      Full description
 * @param severity         AI-determined severity (CRITICAL / HIGH / MEDIUM / LOW)
 * @param status           Lifecycle status (OPEN / IN_PROGRESS / RESOLVED / ESCALATED)
 * @param category         AI-determined category
 * @param affectedServices Comma-separated list of affected service names
 * @param reportedBy       Reporter username
 * @param assignedTo       Assigned engineer
 * @param rootCause        AI-determined root cause
 * @param resolution       Resolution description
 * @param aiSummary        Executive summary generated by the IncidentOrchestrator
 * @param notes            Ordered timeline notes (most recent first)
 * @param createdAt        Creation timestamp
 * @param updatedAt        Last update timestamp
 * @param resolvedAt       Resolution timestamp (null if not resolved)
 */
public record IncidentResponse(
        Long id,
        String title,
        String description,
        String severity,
        String status,
        String category,
        String affectedServices,
        String reportedBy,
        String assignedTo,
        String rootCause,
        String resolution,
        String aiSummary,
        List<NoteResponse> notes,
        LocalDateTime createdAt,
        LocalDateTime updatedAt,
        LocalDateTime resolvedAt
) {

    /** Nested record for a single timeline note. */
    public record NoteResponse(
            Long id,
            String content,
            String noteType,
            String author,
            LocalDateTime createdAt
    ) {
        public static NoteResponse from(IncidentNote note) {
            return new NoteResponse(
                    note.getId(),
                    note.getContent(),
                    note.getNoteType(),
                    note.getAuthor(),
                    note.getCreatedAt()
            );
        }
    }

    /**
     * Factory method — maps domain objects to the response record.
     *
     * @param incident the incident entity
     * @param notes    timeline notes for the incident
     */
    public static IncidentResponse from(Incident incident, List<IncidentNote> notes) {
        return new IncidentResponse(
                incident.getId(),
                incident.getTitle(),
                incident.getDescription(),
                incident.getSeverity(),
                incident.getStatus(),
                incident.getCategory(),
                incident.getAffectedServices(),
                incident.getReportedBy(),
                incident.getAssignedTo(),
                incident.getRootCause(),
                incident.getResolution(),
                incident.getAiSummary(),
                notes.stream().map(NoteResponse::from).toList(),
                incident.getCreatedAt(),
                incident.getUpdatedAt(),
                incident.getResolvedAt()
        );
    }
}
